sudo: required
services:
  - docker # install docker 

before_install:
  #  build dev image
  - docker build -t isdance/react-test -f ./client/Dockerfile.dev ./client

script:
  # test dev image
  - docker run isdance/react-test npm test -- --coverage

after_success:
  #  build production images
  - docker build -t isdance/multi-client ./client
  - docker build -t isdance/multi-nginx ./nginx
  - docker build -t isdance/multi-server ./server
  - docker build -t isdance/multi-worker ./worker

  # login to the docker CLI
  - docker login -u "$DOCER_ID" -p "$DOCKER_PASSWORD"
  
  # push to docker hub
  - docker push isdance/multi-client
  - docker push isdance/multi-nginx
  - docker push isdance/multi-server
  - docker push isdance/multi-worker
