version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx: 
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev # build a custom nginx image 
    ports:
      - '3050:80' # 3050 is a arbitrary number
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # use node_modules from container, don't map back to local
      - ./server:/app
    environment: # environment for this container
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # use node_modules from container, don't map back to local
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # use node_modules from container, don't map back to local
      - ./worker:/app
    environment: # environment for this container
      - REDIS_HOST=redis
      - REDIS_PORT=6379

